[theme]
primaryColor = "#0A3D62"         # deep trust-blue
backgroundColor = "#F7F9FC"      # soft off-white
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1D2545"           # dark navy text
font = "sans serif"
